import yfinance as yf
from pymongo import MongoClient
import os
import json
from datetime import datetime, timezone

class NewsItem:
    def __init__(self,title:str,content:str):
        self.title:str = title
        self.content:str = content
        self.date:datetime = datetime.now(timezone.utc)

def getNews() -> list[dict]:
    tickerName = "ADBE"
    ticker = yf.Ticker(tickerName)

    newsData = ticker.get_news(10,tab="press releases")
    news = []
    for n in newsData:
        content = n["content"]
        title = content["title"]
        summary = content["summary"]
        news.append(transformToDoc(NewsItem(title,summary)))
    return news

def transformToDoc(newsItem:NewsItem) -> dict:
    return {
        "content":newsItem.content,
        "title":newsItem.title,
        "date":newsItem.date
            }

def main():
    NEWS_COL_NAME = "news"
    print("[LOG] Adding initial articles, the rest should be generated by cron orr something")
    try:
        with open("appsettings.json","r",encoding="utf-8") as f:
            config = json.load(f)
            conn_str = config["MongoSettings"]["ConnectionString"]
            client = MongoClient(conn_str)
            db_name = config["MongoSettings"]["DatabaseName"];
            db = client[db_name]
            db.create_collection(NEWS_COL_NAME)
            coll = db[NEWS_COL_NAME]
            newsList: list[dict] = getNews()
            coll.insert_many(newsList)
    except Exception as e:
        print(e)

main()



